### ISSUE TITLE
execute package on create server

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-go-cli#38]
can you put an example or help me with my config for executing a package during server build.  I can't seem to get it right.

```
clc server create --name HYPER --description "HYPER" --group-name "hyper" --template-name WIN2012R2DTC-64 --network-name "DMZ_10.100.191.0/24" --cpu 2 --memory-gb 8 --type hyperscale --storage-type hyperscale --anti-affinity-policy-name "hyper" --packages ["b229535c-a313-4a31-baf8-6aa71ff4b9ed"]
```

I always get 'b229535c-a313-4a31-baf8-6aa71ff4b9ed must be an object specified either in JSON or in key=value,.. format'

I'm sure i've just got something wrong in the call.

**Comment by ldmberman** [comment]
There should be `{'packageId':'b229535c-a313-4a31-baf8-6aa71ff4b9ed'}` instead of plain `b229535c-a313-4a31-baf8-6aa71ff4b9ed`. Or, `--packages packageId=b229535c-a313-4a31-baf8-6aa71ff4b9ed` would also fit.

Admittedly, it has to be exposed in help as it is generally the case for other options here.

**Comment by chrislittle** [comment]
thx
