### ISSUE TITLE
Generate cli skeleton

### ISSUE THREAD

**Issue by gavin-lai** [CenturyLinkCloud/clc-go-cli#44]
Good morning,
CLI version: 2016-Jan-06
I have been trying to have the --generate-cli-skeleton working, from both the example and from trying myself. From the example:
clc group list --filter 'servers-count>0' --generate-cli-skeleton > groups_with_servers.json 
clc group list --from-file groups_with_servers.json
Output: All does not accept any value.
While this works:
clc server list --all --query details.host-name --generate-cli-skeleton > servername.json
clc server list --from-file servername.json
[
    {
        "HostName": "va1rfpdweb401"
    },
    {
        "HostName": "va1rfpdweb202"
    },
    {
        "HostName": "va1rfpdweb103"
    },
    {
        "HostName": "va1rfpdweb301"
    }
]
But clc server delete --from-file servername.json would not work:
Unknown option or argument: `All`.

Is that normal behaviour?
Thanks
Gavin

**Comment by ldmberman** [comment]
Hi @gavin-lai ,

As of your first example

```
clc group list --filter 'servers-count>0' --generate-cli-skeleton > groups_with_servers.json
clc group list --from-file groups_with_servers.json
```

there is a bug, indeed. The `group list` and `server list` commands do not generate the skeleton properly unless the `--all` option is specified. As a workaround, you can remove the `"All":{"Set":false},` part from `groups_with_servers.json`.

In your second example

```
clc server delete --from-file servername.json
```

everything works as expected. The `--from-file` option simply takes the arguments from the input file and applies them to the command. Since you use a set of arguments for a different command here the tool complains about an unknown argument.

**Comment by gavin-lai** [comment]
A follow on question, can --filter be used for items under a first level item, like details.power-state?  Or there is a better way doing it?
Thanks
Gavin

**Comment by ldmberman** [comment]
Unfortunately, `--filter` does not work with the inner fields.

You might consider using [the jq tool](https://stedolan.github.io/jq/) for complex JSON processing. For example, you may first query by the host name and power state:

```
./dev server list --query 'details.{host-name,power-state}'
```

and then filter the paused servers using jq:

```
./dev server list --query 'details.{host-name,power-state}' | jq '.[] | select(.PowerState == "paused")'
```

**Comment by ldmberman** [comment]
@gavin-lai @jruckle was fixed in [the latest release](https://github.com/CenturyLinkCloud/clc-go-cli/releases/tag/2016-03-28).
