### ISSUE TITLE
You can not specify an IP address on the clc server import

### ISSUE THREAD

**Issue by dylanhughes** [CenturyLinkCloud/clc-go-cli#96]
We have a customer that is self importing in a mitel telephone application that needs to be brought up on a specific IP address so we need to be able to specify -ipaddress on the clc server import command in clc go.

**Comment by richardcase** [comment]
I'll work on this.

**Comment by richardcase** [comment]
Looking at the underlying API (v2) consumed by the CLI there is no option to specify IP address when importing:

https://www.ctl.io/api-docs/v2/#servers-import-server

You can specify a network and it will assign an address to the server from those available for the network.  We need to get the underling API updated so that it supports the the 'ipAddress' option like the create server API call (https://www.ctl.io/api-docs/v2/#servers-create-server).

**Comment by richardcase** [comment]
@dylanhughes  - can this be closed as the underlying v2 API doesn't support the functionality?

**Comment by dylanhughes** [comment]
Richard,

Yes please close this request.

Thank you for your time.

Regards,

Dylan Hughes
Cloud Onboarding Architect

230 Wharfedale Road, Winnersh Triangle, Wokingham, Berkshire, RG41 5TP, UK
desk line: +44 (0) 118 3094748
mobile: +44 (0) 7557 284675
Dylan.hughes@centurylink.com<mailto:Dylan.hughes@centurylink.com>

[cid:image001.png@01D2FBD5.FCA20C90][cid:image002.png@01D2FBD5.FCA20C90]<http://www.centurylink.co.uk/>[cid:image003.png@01D2FBD5.FCA20C90]<https://twitter.com/centurylinkemea>[cid:image004.png@01D2FBD5.FCA20C90]<https://www.linkedin.com/company/centurylink-emea>[cid:image005.png@01D2FBD5.FCA20C90]<https://www.youtube.com/user/CenturyLinkTech>
Centurylink Limited | Registered in England | Registration No: 09626356
Registered Office: Eskdale Road, Winnersh Triangle, Wokingham, Berkshire
